// Generated by gencpp from file ros_threads/TimeResponse.msg
// DO NOT EDIT!


#ifndef ROS_THREADS_MESSAGE_TIMERESPONSE_H
#define ROS_THREADS_MESSAGE_TIMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_threads
{
template <class ContainerAllocator>
struct TimeResponse_
{
  typedef TimeResponse_<ContainerAllocator> Type;

  TimeResponse_()
    : Time()  {
    }
  TimeResponse_(const ContainerAllocator& _alloc)
    : Time(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Time_type;
  _Time_type Time;




  typedef boost::shared_ptr< ::ros_threads::TimeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_threads::TimeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TimeResponse_

typedef ::ros_threads::TimeResponse_<std::allocator<void> > TimeResponse;

typedef boost::shared_ptr< ::ros_threads::TimeResponse > TimeResponsePtr;
typedef boost::shared_ptr< ::ros_threads::TimeResponse const> TimeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_threads::TimeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_threads::TimeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_threads

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_threads::TimeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_threads::TimeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_threads::TimeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_threads::TimeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_threads::TimeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_threads::TimeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_threads::TimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a51d460e605a9c6545a3645e45e7d27e";
  }

  static const char* value(const ::ros_threads::TimeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa51d460e605a9c65ULL;
  static const uint64_t static_value2 = 0x45a3645e45e7d27eULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_threads::TimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_threads/TimeResponse";
  }

  static const char* value(const ::ros_threads::TimeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_threads::TimeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Time\n\
\n\
";
  }

  static const char* value(const ::ros_threads::TimeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_threads::TimeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_threads::TimeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_threads::TimeResponse_<ContainerAllocator>& v)
  {
    s << indent << "Time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_THREADS_MESSAGE_TIMERESPONSE_H
